### ISSUE TITLE
非拨号主路由好像不行捏，获取到的绑定ip是内网地址，提示未开通

### ISSUE THREAD

**Issue by IMRUMI** [Diciya/luci-app-broadbandacc#6]
2023/04/27 09:01:30 宽带助手启动中...
2023/04/27 09:01:30 绑定IP地址: 192.168.1.2
2023/04/27 09:01:31 服务接口连接正常
2023/04/27 09:01:32 出口IP地址: ***.***.***.***
2023/04/27 09:01:32 宽带: ******
2023/04/27 09:01:32 提速开始时间: 2023-04-27 09:01:31
2023/04/27 09:01:32 一类上行带宽50M提速截至时间: 
2023/04/27 09:01:32 二类上行带宽100M提速截至时间: 
2023/04/27 09:01:32 下行带宽500M提速截至时间: 
2023/04/27 09:01:32 上行未开通
2023/04/27 09:01:32 下行未开通

**Comment by Diciya** [comment]
宽带服务商是什么

**Comment by Diciya** [comment]
> 2023/04/27 09:01:30 宽带助手启动中... 2023/04/27 09:01:30 绑定IP地址: 192.168.1.2 2023/04/27 09:01:31 服务接口连接正常 2023/04/27 09:01:32 出口IP地址: _**.**_._**.**_ 2023/04/27 09:01:32 宽带: ****** 2023/04/27 09:01:32 提速开始时间: 2023-04-27 09:01:31 2023/04/27 09:01:32 一类上行带宽50M提速截至时间: 2023/04/27 09:01:32 二类上行带宽100M提速截至时间: 2023/04/27 09:01:32 下行带宽500M提速截至时间: 2023/04/27 09:01:32 上行未开通 2023/04/27 09:01:32 下行未开通

宽带服务商是什么

**Comment by Diciya** [comment]
如果你已经开通服务，并且能够提速，这可能是软件显示的bug，后续会进行修复

**Comment by IMRUMI** [comment]
> 
电信

> 如果你已经开通服务，并且能够提速，这可能是软件显示的bug，后续会进行修复
开通服务了，测了下速没成功

**Comment by IMRUMI** [comment]
> 如果你已经开通服务，并且能够提速，这可能是软件显示的bug，后续会进行修复

电信，开通服务了，测了下速没成功

**Comment by Diciya** [comment]
这个界面显示是怎么样的，还有我的套餐的截图
![JZFC0HP3IEBH~RZJ14 J98V](https://user-images.githubusercontent.com/76506087/234746651-5b5bc52a-4247-45d2-8f77-d103864194a5.png)

**Comment by Diciya** [comment]
> > 如果你已经开通服务，并且能够提速，这可能是软件显示的bug，后续会进行修复
> 
> 电信，开通服务了，测了下速没成功

确保整个链路都能达到提速带宽的

**Comment by IMRUMI** [comment]
> > > 如果你已经开通服务，并且能够提速，这可能是软件显示的bug，后续会进行修复
> > 
> > 
> > 电信，开通服务了，测了下速没成功
> 
> 确保整个链路都能达到提速带宽的

应该是我这边的问题，我重装后重新购买可以了
